version: '3.3'

services:
  db:
    image: mysql:5.7
    container_name: "db"
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_DATABASE: neginet
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    networks:
      - back

  back:
    image: neginet/back
    container_name: "back"
    depends_on:
      - db
    build:
      context: ./back/
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    networks:
      - back

  front:
    image: neginet/front
    container_name: "front"
    depends_on:
      - back
    build:
      context: ./front/
      dockerfile: Dockerfile
    restart: always
    ports:
      - "80:80"
    networks:
      - back

networks:
  back:

volumes:
  db_data: {}
